export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';

// New actions added by Xinghang
export const LOAD_MENUS_SUCCESS = 'LOAD_MENUS_SUCCESS';
export const CREATE_MENU_SUCCESS = 'CREATE_MENU_SUCCESS';
export const UPDATE_MENU_SUCCESS = 'UPDATE_MENU_SUCCESS';
export const DELETE_MENU_SUCCESS = 'DELETE_MENU_SUCCESS';

export const LOAD_CART_SUCCESS = 'LOAD_CART_SUCCESS';
export const CREATE_CART_SUCCESS = 'CREATE_CART_SUCCESS';
// export const UPDATE_MENU_SUCCESS = 'UPDATE_MENU_SUCCESS';
export const DELETE_CART_SUCCESS = 'DELETE_CART_SUCCESS';
export const EMPTY_CART_SUCCESS = 'EMPTY_CART_SUCCESS';

// new actions added by Shikun
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USER_SESSION_SUCCESS = 'LOAD_USER_SESSION_SUCCESS';
export const SIGN_IN_USER_SUCCESS = 'SIGN_IN_USER_SUCCESS';
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
export const LOG_OUT_USER_SUCCESS = 'LOG_OUT_USER_SUCCESS';


export const SAVE_ORDER_SUCCESS = 'SAVE_ORDER_SUCCESS';
export const LOAD_ORDER_SUCCESS = 'LOAD_ORDER_SUCCESS';

